import { SearchSuggestionDataType } from "@/types/types";


export const search_suggestion_services_data: string[] =
    [
        "Aircon Servicing",
        "Anti mould treatment",
        "Car wash",
        "Carpentry and Interior design",
        "Carpentry Service",
        "Carpet cleaning",
        "Cat Bidder",
        "Cat Helper - The professional helper you will ever need",
        "Cat Home Boarding",
        "Changing of toilet vanity for Sophia",
        "Cleaning promotion for $338 and for 18 hours",
        "Covid disinfecting service / Islam cleansing",
        "Curtain steam cleaning",
        "Curve Arch",
        "Declutter with our cats",
        "Disposal and moving of bulky items",
        "Efflorescence Prevention (Tiled Surface)",
        "Electrical Cat Service",
        "Electrical Service",
        "Epoxy grouting",
        "Home Appliances Repair Service",
        "Installation and replacement of toilet seat cover",
        "Installation of shower accessories",
        "Installation of toilet bowl",
        "Installation of water heater",
        "Installation of water tap and basin",
        "Knoc Knoc cleaning trial (3 hours)",
        "Laying of plastic sheets and protection covers",
        "Lego painting at your choice",
        "Locksmith Service",
        "Marble gum for Hazel",
        "Mattress cleaning",
        "Momento/Limewash painting",
        "Moving service by our cats",
        "No Hacking Balcony Waterproofing (Tiled Surface)",
        "No Hacking Swimming Pool Waterproofing",
        "No Hacking Toilet Waterproofing (Tiled Surface)",
        "Painting - 1 room apartment",
        "Painting - 2 room apartment",
        "Painting - 3 room apartment",
        "Painting - 4 room apartment",
        "Painting - 5 room apartment",
        "Painting - Executive Apartment / Executive Maisonette (EA/EM)",
        "Part-time Cook",
        "Pest control service",
        "Pet Grooming service(Cat)",
        "Pet Grooming service(Dog)",
        "Pet Sitting Service",
        "Plastering and fixing of walls",
        "Repair service for Ravinder",
        "Upholstery Cleaning - sofa",
        "Vinyl flooring supply and installation",
        "Wallpaper - 3 room",
        "Wallpaper - 4 room",
        "Wallpaper - 5 room",
        "Wood and furniture restoration",
        "10K Servicing",
        "Accident Claims",
        "Alignment service",
        "Battery change",
        "Car Aircon Servicing",
        "Car fumigation and disinfection",
        "Car Modd",
        "Ceramic Coating",
        "Solar film",
        "Tow Truck Service",
        "Wash & Polish",
    ]
